name: laborus_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  badges: ^3.1.1
  intl: ^0.18.1
  smooth_page_indicator: ^1.1.0
  carousel_slider: ^4.2.1
  go_router: ^12.1.1
  provider: ^6.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path: ^1.8.3
  timeline_tile: ^2.0.0
  percent_indicator: ^4.2.3
  readmore: ^2.2.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

flutter_icons:
  image_path: "assets/img/logo.png"
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/img/

flutter_native_splash:
  color: "#7000B5"
  image: assets/img/laborus_light2.png
  android_12:
    color: "#7000B5"
    image: assets/img/laborus_light2.png
  web: false
  fullscreen: true
