name: laborus_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  badges: ^3.1.1
  intl: ^0.18.1
  smooth_page_indicator: ^1.1.0
  carousel_slider: ^4.2.1
  go_router: ^12.1.1
  provider: ^6.1.1
  shared_preferences: ^2.2.3
  flutter_dotenv: ^5.2.1
  http: ^1.2.2


  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
#   flutter_launcher_icons: ^0.13.1
#   flutter_native_splash: ^2.4.0

# flutter_icons:
#   image_path: "assets/img/logo.png"
#   android: true
#   ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/img/
    - .env


  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto_light.ttf
          weight: 300
        - asset: assets/fonts/roboto_medium.ttf
          weight: 500
        - asset: assets/fonts/roboto_bold.ttf
          weight: 700

    - family: Inter
      fonts:
        - asset: assets/fonts/inter_light.ttf
          weight: 300
        - asset: assets/fonts/inter_medium.ttf
          weight: 500
        - asset: assets/fonts/inter_bold.ttf
          weight: 700
        - asset: assets/fonts/inter_bold.ttf
          weight: 800 
        - asset: assets/fonts/inter_bold.ttf
          weight: 900

# flutter_native_splash:
#   color: "#7000B5"
#   image: assets/img/laborus_light2.png
#   android_12:
#     color: "#7000B5"
#     image: assets/img/laborus_light2.png
#   web: false
#   fullscreen: true
